export const FRASES = [
  { pt: "Eu gosto de cachorros", en: ["I", "like", "dogs"] },
  { pt: "Bom dia, professor", en: ["Good", "morning", "teacher"] },
  { pt: "Ela tem um gato preto", en: ["She", "has", "a", "black", "cat"] },
  { pt: "Nós comemos arroz e frango", en: ["We", "eat", "rice", "and", "chicken"] },
  { pt: "Eu bebo café todo dia", en: ["I", "drink", "coffee", "every", "day"] },
  { pt: "Ele é meu amigo", en: ["He", "is", "my", "friend"] },
  { pt: "A maçã é vermelha", en: ["The", "apple", "is", "red"] },
  { pt: "Hoje é segunda-feira", en: ["Today", "is", "Monday"] },
  { pt: "Meu aniversário é em maio", en: ["My", "birthday", "is", "in", "May"] },
  { pt: "Por favor, feche a porta", en: ["Please", "close", "the", "door"] },
  { pt: "Eu tenho um cachorro branco", en: ["I", "have", "a", "white", "dog"] },
  { pt: "Ela come pão no café da manhã", en: ["She", "eats", "bread", "for", "breakfast"] },
  { pt: "Nós vamos à escola na segunda-feira", en: ["We", "go", "to", "school", "on", "Monday"] },
  { pt: "Ele bebe água todos os dias", en: ["He", "drinks", "water", "every", "day"] },
  { pt: "O leão é grande e forte", en: ["The", "lion", "is", "big", "and", "strong"] },
  { pt: "Eu gosto de queijo e frango", en: ["I", "like", "cheese", "and", "chicken"] },
  { pt: "Meu gato é preto e branco", en: ["My", "cat", "is", "black", "and", "white"] },
  { pt: "Dezembro é o último mês do ano", en: ["December", "is", "the", "last", "month", "of", "the", "year"] },
  { pt: "Ela tem um pássaro amarelo", en: ["She", "has", "a", "yellow", "bird"] },
  { pt: "Nós bebemos leite todas as manhãs", en: ["We", "drink", "milk", "every", "morning"] },
  { pt: "Com licença, onde está o banheiro", en: ["Excuse", "me", "where", "is", "the", "bathroom"] },
  { pt: "Desculpa, eu não entendi", en: ["Sorry", "I", "did", "not", "understand"] },
  { pt: "O macaco gosta de banana", en: ["The", "monkey", "likes", "banana"] },
  { pt: "Ela bebe suco de laranja hoje", en: ["She", "drinks", "orange", "juice", "today"] },
  { pt: "Eu como salada e sopa", en: ["I", "eat", "salad", "and", "soup"] },
  { pt: "A tartaruga é lenta mas forte", en: ["The", "turtle", "is", "slow", "but", "strong"] },
  { pt: "Ele tem doze anos", en: ["He", "is", "twelve", "years", "old"] },
  { pt: "Amanhã é sábado", en: ["Tomorrow", "is", "Saturday"] },
  { pt: "Minha mãe está na cozinha", en: ["My", "mother", "is", "in", "the", "kitchen"] },
  { pt: "Meu pai lê o livro toda noite", en: ["My", "father", "reads", "the", "book", "every", "night"] },
  { pt: "A chave está em cima da mesa", en: ["The", "key", "is", "on", "the", "table"] },
  { pt: "Minha irmã tem um computador novo", en: ["My", "sister", "has", "a", "new", "computer"] },
  { pt: "Meu avô senta na cadeira azul", en: ["My", "grandfather", "sits", "in", "the", "blue", "chair"] },
];